# Clock signal
#set_property PACKAGE_PIN W5 [get_ports clk]		
#	set_property IOSTANDARD LVCMOS33 [get_ports clk]
#	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
#   create_clock -name design_1_gmii_to_rgmii_0_0_rgmii_rx_clk -period 8
 
# Dato1
set_property PACKAGE_PIN V17 [get_ports {dato1[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[0]}]
set_property PACKAGE_PIN V16 [get_ports {dato1[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[1]}]
set_property PACKAGE_PIN W16 [get_ports {dato1[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[2]}]
set_property PACKAGE_PIN W17 [get_ports {dato1[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[3]}]
set_property PACKAGE_PIN W15 [get_ports {dato1[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[4]}]
set_property PACKAGE_PIN V15 [get_ports {dato1[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[5]}]
set_property PACKAGE_PIN W14 [get_ports {dato1[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[6]}]
set_property PACKAGE_PIN W13 [get_ports {dato1[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato1[7]}]

# Dato2
set_property PACKAGE_PIN V2 [get_ports {dato2[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[0]}]
set_property PACKAGE_PIN T3 [get_ports {dato2[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[1]}]
set_property PACKAGE_PIN T2 [get_ports {dato2[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[2]}]
set_property PACKAGE_PIN R3 [get_ports {dato2[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[3]}]
set_property PACKAGE_PIN W2 [get_ports {dato2[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[4]}]
set_property PACKAGE_PIN U1 [get_ports {dato2[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[5]}]
set_property PACKAGE_PIN T1 [get_ports {dato2[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[6]}]
set_property PACKAGE_PIN R2 [get_ports {dato2[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[7]}]

# Salida
set_property PACKAGE_PIN V13 [get_ports {salida[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[0]}]
set_property PACKAGE_PIN V3 [get_ports {salida[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[1]}]
set_property PACKAGE_PIN W3 [get_ports {salida[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[2]}]
set_property PACKAGE_PIN U3 [get_ports {salida[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[3]}]
set_property PACKAGE_PIN P3 [get_ports {salida[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[4]}]
set_property PACKAGE_PIN N3 [get_ports {salida[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[5]}]
set_property PACKAGE_PIN P1 [get_ports {salida[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[6]}]
set_property PACKAGE_PIN L1 [get_ports {salida[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {salida[7]}]
	
#Op_Code
set_property PACKAGE_PIN W7 [get_ports {op_code[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[0]}]
set_property PACKAGE_PIN W6 [get_ports {op_code[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[1]}]
set_property PACKAGE_PIN U8 [get_ports {op_code[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[2]}]
set_property PACKAGE_PIN V8 [get_ports {op_code[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[3]}]
set_property PACKAGE_PIN U5 [get_ports {op_code[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[4]}]
set_property PACKAGE_PIN V5 [get_ports {op_code[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[5]}]