webtalk_init -webtalk_dir E:/arqui_2020/git/arqui-2022/vivado/tp1_v2/tp1_v2.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_alu_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 26 21:29:32 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c0235b0d-0069-4a79-84b8-4f9c5040770c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "46dee375a92d4846a1e389ce748e1f90" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700G with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "400 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9572_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3124198259 -regid "" -xml E:/arqui_2020/git/arqui-2022/vivado/tp1_v2/tp1_v2.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_alu_time_synth/webtalk/usage_statistics_ext_xsim.xml -html E:/arqui_2020/git/arqui-2022/vivado/tp1_v2/tp1_v2.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_alu_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm E:/arqui_2020/git/arqui-2022/vivado/tp1_v2/tp1_v2.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_alu_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
