# Clock signal
#set_property PACKAGE_PIN W5 [get_ports clk]		
#	set_property IOSTANDARD LVCMOS33 [get_ports clk]
#	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
#Switch
set_property PACKAGE_PIN U16 [get_ports {switch[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property PACKAGE_PIN E19 [get_ports {switch[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property PACKAGE_PIN U19 [get_ports {switch[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property PACKAGE_PIN V19 [get_ports {switch[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property PACKAGE_PIN W18 [get_ports {switch[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property PACKAGE_PIN U15 [get_ports {switch[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property PACKAGE_PIN U14 [get_ports {switch[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property PACKAGE_PIN V14 [get_ports {switch[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]

#Salida
set_property PACKAGE_PIN V13 [get_ports {w_salida[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[0]}]
set_property PACKAGE_PIN V3 [get_ports {w_salida[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[1]}]
set_property PACKAGE_PIN W3 [get_ports {w_salida[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[2]}]
set_property PACKAGE_PIN U3 [get_ports {w_salida[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[3]}]
set_property PACKAGE_PIN P3 [get_ports {w_salida[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[4]}]
set_property PACKAGE_PIN N3 [get_ports {w_salida[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[5]}]
set_property PACKAGE_PIN P1 [get_ports {w_salida[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[6]}]
set_property PACKAGE_PIN L1 [get_ports {w_salida[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w_salida[7]}]

#Botones
set_property PACKAGE_PIN W7 [get_ports {b_dato1[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b_dato1[0]}]
set_property PACKAGE_PIN W6 [get_ports {b_dato2[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b_dato2[0]}]
set_property PACKAGE_PIN U8 [get_ports {b_code[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b_code[0]}]
set_property PACKAGE_PIN V8 [get_ports {clk[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {clk[0]}]