# Clock signal
set_property PACKAGE_PIN W5 [get_ports i_clk]	
	set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports i_clk]
	
	
# Switch
set_property PACKAGE_PIN V17 [get_ports {i_switch[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[0]}]
set_property PACKAGE_PIN V16 [get_ports {i_switch[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[1]}]
set_property PACKAGE_PIN W16 [get_ports {i_switch[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[2]}]
set_property PACKAGE_PIN W17 [get_ports {i_switch[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[3]}]
set_property PACKAGE_PIN W15 [get_ports {i_switch[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[4]}]
set_property PACKAGE_PIN V15 [get_ports {i_switch[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[5]}]
set_property PACKAGE_PIN W14 [get_ports {i_switch[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[6]}]
set_property PACKAGE_PIN W13 [get_ports {i_switch[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_switch[7]}]

## Dato2
#set_property PACKAGE_PIN V2 [get_ports {dato2[0]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[0]}]
#set_property PACKAGE_PIN T3 [get_ports {dato2[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[1]}]
#set_property PACKAGE_PIN T2 [get_ports {dato2[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[2]}]
#set_property PACKAGE_PIN R3 [get_ports {dato2[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[3]}]
#set_property PACKAGE_PIN W2 [get_ports {dato2[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[4]}]
#set_property PACKAGE_PIN U1 [get_ports {dato2[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[5]}]
#set_property PACKAGE_PIN T1 [get_ports {dato2[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[6]}]
#set_property PACKAGE_PIN R2 [get_ports {dato2[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dato2[7]}]
	
# LEDs with carry
set_property PACKAGE_PIN U16 [get_ports {o_led[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]
set_property PACKAGE_PIN E19 [get_ports {o_led[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
set_property PACKAGE_PIN U19 [get_ports {o_led[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[2]}]
set_property PACKAGE_PIN V19 [get_ports {o_led[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[3]}]
set_property PACKAGE_PIN W18 [get_ports {o_led[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[4]}]
set_property PACKAGE_PIN U15 [get_ports {o_led[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[5]}]
set_property PACKAGE_PIN U14 [get_ports {o_led[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[6]}]
set_property PACKAGE_PIN V14 [get_ports {o_led[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_led[7]}]
set_property PACKAGE_PIN V13 [get_ports {o_carry_bit}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_carry_bit}]
	
##Op_Code
#set_property PACKAGE_PIN W7 [get_ports {op_code[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[0]}]
#set_property PACKAGE_PIN W6 [get_ports {op_code[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[1]}]
#set_property PACKAGE_PIN U8 [get_ports {op_code[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[2]}]
#set_property PACKAGE_PIN V8 [get_ports {op_code[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[3]}]
#set_property PACKAGE_PIN U5 [get_ports {op_code[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[4]}]
#set_property PACKAGE_PIN V5 [get_ports {op_code[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {op_code[5]}]

##Buttons (ENABLE)
set_property PACKAGE_PIN U18 [get_ports i_enable[0]]						
	set_property IOSTANDARD LVCMOS33 [get_ports i_enable[0]]
set_property PACKAGE_PIN T18 [get_ports i_enable[1]]						
	set_property IOSTANDARD LVCMOS33 [get_ports i_enable[1]]
set_property PACKAGE_PIN W19 [get_ports i_enable[2]]						
	set_property IOSTANDARD LVCMOS33 [get_ports i_enable[2]]
	
